### PR TITLE
Complete the Backup + Restore documentation for PKS

### PR DESCRIPTION
**Pull request by gmrodgers**
The branch is our first step in completing the Backup + Restore docs for PKS using BBR.

After conversation with VMware folks we saw that some things were missing/unclear, specifically:
*For Backup*:
+ What do we mean by "Network Resources" when we say we don't support it
+ How to back and restore Ops Manager (or export and import Settings)
+ How to back and restore the BOSH Director
+ NSX-t is not yet validated to be unsupported so we changed the language around that

*For Restore*:
+ How to restore OpsManager
+ How to restore the BOSH director
+ How to fix stale references to stemcells, etc (bosh cck)
+ How to redeploy PKS Control Plane
+ How to redeploy K8s clusters (refer to on-demand service instances restore)

We have fused the two previous backup files for clusters and control plane into one file:
+ `bbr-backup.html`

We have fused the two previous backup files for clusters and control plane into one file:
+ `bbr-restore.html`

More information was added to these files in order make our docs, for the backup and restore processes, more complete (mentioned above).

These would need to be added/changed to the Subnav menu on the side (couldn't find this in layout repo, could you link for future reference?).

Questions about style, best practices:
+ In some cases we link directly to the PAS docs, is this done correctly/permitted?  An example of this is using the Opsmanager API to access credentials, or uploading a stemcell.
+ What is the capitalisation of the BOSH Director meant to be? Lowercase or uppercase? Is director on its own okay. 

This branch fills in gaps that were previously missing in our documentation.  If there is anything that is unclear or if you compare the two guides and find something missing in PKS, let us know or ask!

Thanks,
Platform Recovery Team

PS Also removed whitespace + reordered
[#165997988]

### CODE REVIEW

**Comment by animatedmax** [comment]
Hi Platform Recovery Team,

Thank you for this incredible effort.

To answer your requests:

1. For the PKS documentation, the subnav is `master_middleman/source/subnavs/pks_subnav.erb` in the `https://github.com/pivotal-cf/docs-book-pks/` GitHub repository.

    We try to separate the content from the presentation, and so the Subnav menu is kept in a separate "book" repository. This way, we can use the same repository in multiple different documentation sets.

2. To link to the latest released version of any of our documentation, leave out the version number in the URL. So for these two links use the following: 

    * Backup: https://docs.pivotal.io/pivotalcf/customizing/backup-restore/backup-pcf-bbr.html#procedure
    * Restore: https://docs.pivotal.io/pivotalcf/customizing/backup-restore/restore-pcf-bbr.html#restore

    These link will automatically redirect to the latest version, so right now they'll redirect to `https://docs.pivotal.io/pivotalcf/2-5/`, and when PAS 2.6 releases they'll redirect to `https://docs.pivotal.io/pivotalcf/2-6/`.

Thanks again!

**Comment by ograves-pivotal** [comment]
@gmrodgers @connor
I've started working on this update using a branch within our PKS Docs repo.  The new branch off of master can be seen here: https://github.com/pivotal-cf/docs-pks/compare/story-bbr-director-%23166323779. I will perform all style corrections in this new branch.

The branch now contains all of your Herculean efforts listed above.  I will edit for style as well as modify the subnav elements necessary for proper linking and navigation.

**Comment by gmrodgers** [comment]
Hey @ograves-pivotal 
We have finished off the last of our addings in/takings out.  There is now just two bbr files (backup and restore).  Please rebase your branch with our to get the new changes!  There are some conflicts in the file we have deleted!  Feel free to delete it/port over your changes as they are now moved from: `bbr-restore-cluster.html.md.erb` to `bbr-restore.html.md.erb`

**Comment by alamages** [comment]
Work from this PR has been updated from @ograves-pivotal. We have opened a new PR against his branch to address some comments. Let's close this PR and come up with a new one based on Oliver's branch.

**Comment by gmrodgers** [comment]
Closing PR as other branch (https://github.com/pivotal-cf/docs-pks/compare/story-bbr-director-%23166323779) is being used

**Pull request closed without merging**
