### PR TITLE
Update number of worker nodes screenshot, remove max

### PR DESCRIPTION
**Pull request by lparis**
Applies to 1.3 and 1.4/master. Sending to Merlin and Ryan for approval. Thanks.

### CODE REVIEW

**Comment by bentarnoff** [comment]
Thanks @lparis! My understanding is that there's no upper limit to the number of worker nodes unless you're deploying vSphere on NSX-T, in which case the upper limit is 250. Is this correct?

**Comment by bentarnoff** [comment]
@lparis After discussion with Ryan, Jaime, and others, I've determined the following:

There is an upper limit of 250 for NSX-T, and no upper limit for vSphere w/o NSX-T or any other IaaSes, but we have only tested up to 200 workers.

We'll update the docs to reflect!

**Comment by lparis** [comment]
Great. Thanks for getting to the bottom of this.

**Comment by virtmerlin** [comment]
The PR works for me.

**Comment by mjgutermuth** [comment]
Thanks @lparis!

**Pull request merged**
