### PR TITLE
Pks bbr all deployments

### PR DESCRIPTION
**Pull request by gmrodgers**
Hey folks,

This PR updates the docs to instruct people to use the `--all-deployments` flag when backing up their cluster deployments on PKS.  This is the recommended way of doing this and should be present in `1.3` onwards.  So please port this to all versions `1.3` onwards!

Please remove this line in versions `1.4` onwards but keep for version `1.3`.
[* BBR can only back up a single-master cluster.](https://github.com/gmrodgers/docs-pks/blob/44d856856b69e6d23fad320d80970df5cc561616/bbr-backup-cluster.html.md.erb#L18)

We also wanted to change the subnav headings for backing up and restoring a cluster deployments, but we did not have access to the `docs-book-pks` repo.  If you could change the two headings as shown in the `git diff` below:

```diff
diff --git a/master_middleman/source/subnavs/pks_subnav.erb b/master_middleman/source/subnavs/pks_subnav.erb
index 6bcaf29..0620f3f 100644
--- a/master_middleman/source/subnavs/pks_subnav.erb
+++ b/master_middleman/source/subnavs/pks_subnav.erb
@@ -317,10 +317,10 @@
             <a href="/runtimes/pks/1-3/bbr-restore.html">Restoring the PKS Control Plane</a>
           </li>
           <li>
-            <a href="/runtimes/pks/1-3/bbr-backup-cluster.html">Backing up the Single Master Cluster</a>
+            <a href="/runtimes/pks/1-3/bbr-backup-cluster.html">Backing up Clusters</a>
           </li>
           <li>
-            <a href="/runtimes/pks/1-3/bbr-restore-cluster.html">Restoring the Single Master Cluster</a>
+            <a href="/runtimes/pks/1-3/bbr-restore-cluster.html">Restoring a Cluster</a>
           </li>
           <li>
             <a href="/runtimes/pks/1-3/bbr-logging.html">BBR Logging</a>
```

If you've anymore questions, drop us a message!

Thanks,
Glen && @alamages

### CODE REVIEW

**Comment by animatedmax** [comment]
Hi @gmrodgers We were told that BBR supports multi-master clusters in PKS 1.4 and later, and so the v1.3 versions are still titled and about _Backing up the Single Master Cluster_ and _Restoring the Single Master Cluster_. We'll update the subnav headings for v1.4, though. Thanks!

**Comment by glestaris** [comment]
thanks, @animatedmax - can we change the subnav to 'Single Master Cluster**s**', since we are promoting the `--all-deployments` feature to backup all your clusters at once. (Same for 'Multi Master Cluster**s**).

**Comment by animatedmax** [comment]
Hi @glestaris We can absolutely change the subnav, but (sorry) I think I'm having a hard time understanding what you want to change it to. Do you want the v1.3 topics to be " Backing up Single Master Clusters" and " Restoring Single Master Clusters"? And the v1.4 topics to be "Backing up Multi Master Clusters" and "Restoring Multi Master Clusters"?

Sorry for my confusion!

**Comment by gmrodgers** [comment]
No problem @animatedmax!

We support backup and restore of both single-master and multi-master clusters as of v1.4.  For v1.3 and lower, we only support backup and restore of single-master clusters.

The `--all-deployments` flag is an implementation detail for backing up all clusters at once (regardless of whether single or multi master).  This is the main bulk of this PR.

The change in subnav title is more about the change from "Cluster" -> "Clusters" when backing up using the `all-deployments` flag as it does all clusters and not one chosen cluster.  We decided to take out the single-master bit of the subnav as we thought it would be cleaner for v1.4 but if we are to more specific it would be:

<= v1.3: "Backing up Single Master Clusters" and "Restoring Single Master Clusters"
v1.4 <=:  "Backing up Clusters" and "Restoring Clusters"

Hope this helps clear things up

**Pull request merged**
