### PR TITLE
Technical review feedback on Management Console docs

### PR DESCRIPTION
**Pull request by stuclem**
Another wave of tech review on the Management Console docs, mostly related to the deployment wizard. More to follow....

### CODE REVIEW

**Comment by stuclem** [comment]
@animatedmax can you please approve so that I can merge and check the formatting? Thanks!

**Comment by stuclem** [comment]
@animatedmax it seems that I don't have merge rights. Can you please merge this for me? Thanks!

**Comment by stuclem** [comment]
Oops - looks like I should have refreshed my page - you already merged. Thanks!

**Comment by animatedmax** [comment]
Hi @stuclem Happy to merge it for you. For what it's worth, you aren't supposed to have merge rights, so we don't need to change anything.

**Pull request merged**
