### PR TITLE
Doc updates

### LINKED ISSUE #397: Cannot add inline policy to policy
https://github.com/pivotal-cf/docs-pks/blob/bf71668ee9efd16f1c9417a2b3040889c0588b68/aws-prepare-env.html.md.erb#L62

You are not given an option to add an inline policy to a policy. What are the correct steps for this?

### PR DESCRIPTION
**Pull request by roberthamel**
closes #397, #398, #401

### CODE REVIEW

**Comment by mjgutermuth** [comment]
Thanks for these great contributions, @roberthamel! We really appreciate it. Can I just ask since I can't see anything on your profile--are you at VMware or Pivotal?

**Comment by roberthamel** [comment]
I am currently with Accenture Pivotal Business Group in New York.

**Comment by mjgutermuth** [comment]
Gotcha. Thanks so much!

**Comment by mjgutermuth** [comment]
Thanks @roberthamel!

**Pull request merged**
