### PR TITLE
Docs pks issue 311 and 313

### PR DESCRIPTION
**Pull request by kroberts7**
Includes space-fix for issue #313

### CODE REVIEW

**Comment by bentarnoff** [comment]
Thanks @kroberts7

**Comment by bentarnoff** [comment]
Hey @kroberts7 are these lines correct? "arn:aws:s3:::outofmemory-pks-bucket"" arn:aws:s3:::outofmemory-pks-bucket/*". They seem specific to @outofmem0ry's installation, and I'm guessing we'd want the S3 buckets to be named something more generic if we're asking users to copy and paste this policy into AWS.

**Comment by kroberts7** [comment]
Hi @bentarnoff 

Oops!  Thanks for catching that.  Yeahhhhh, those were specific to the AWS deploy I assisted him with.

Soooo, reverting back to the original resource policy block, instead of:

{
              "Effect": "Allow",
              "Action": "s3:\*",
              "Resource": [
                  "arn:aws:s3:::kubernetes-\*"
              ]
          },

`If` the s3 bucket requirement is still pertinent (see issue #312 ) then it should be changed to:

{
              "Effect": "Allow",
              "Action": "s3:\*",
              "Resource": [
                  "arn:aws:s3:::kubernetes-*"
              ]
          },


cheers,

**Comment by kroberts7** [comment]
@bentarnoff I will assume the docs team will create the PR for the above at this time.  Please reach out to me if you need me to submit it.  Thanks!

**Comment by bentarnoff** [comment]
@kroberts7 Thanks! Updated.

**Pull request merged**
