### PR TITLE
Add links to sample workbook, tableau reader, and interpretation guide Telemetry docs

### PR DESCRIPTION
**Pull request by fyang-pivotal**
Telemetry docs related changes

### CODE REVIEW

**Comment by fyang-pivotal** [comment]
Hi @animatedmax: Thanks for getting back to us.  Please see my response below. 

> Specific issues:

> 1. We don't use embedded videos. If this video demonstrates how to do something, we need to tell people how to do that something in written, step-by-step procedure, along with context about what they're supposed to do and why.

Got it.  We will revise the first video to be a step by step instruction instead.    

However, for the second video, it meant to be a video walkthrough of this blog [post](https://content.pivotal.io/blog/announcing-enhanced-telemetry-for-pks).  Would you recommend us simply inserting a link to this blog post instead?

> 2. We don't use links to automatically downloaded third-party software.

Are you referring to the `tableau reader` download link?  If so, if we want to point people to where to download the software, how should we link them to it?

> 3. We don't use blind links -- links that lead outside of the page or documentation set without telling people.

As above, can you point out specific examples where this is occurring, so we can correct them?
 
> In most cases, we don't link to external images. If it is impractical to keep copies of the images within the documentation repository, for example if the images are regularly updated in Google drive, then we can link to them, but we need to use the actual link to the images instead of a bit.ly abbreviation.

Got it.  The reason we are using `bit.ly` links is mainly for providing statistics on who is clicking on the link.  In lieu of using `bit.ly` links, does the doc team provide page view analytics?

These images should not be updated often, so we can certainly host them in the documentation repository.

> If you'd like to correct these issues and resubmit, I would recommend working with Lorenzo to help ensure the PR follows technical writing standards and best practices. Thanks!

Thanks for the suggestion.  We weren't aware of the best practices before submitting the PR.  We will certainly fly the next one by Lorenzo first.

cc. @kdudala1 @tanayk2610 @SenatorSupes

**Comment by kdudala1** [comment]
Hi Max,

Thanks for the feedback!

1. Re: embedded videos, we're already documenting how to perform these steps individually. The point of the opt-in video is to illustrate this in visual form for the benefit of users who would rather see this in action instead of reading it. How would you feel about embedding an animated gif instead? 

Please also expand on the rationale for your current policy of not allowing embedded videos. Specifically - what is the concern here? We believe it would be beneficial to allow users to see these materials in-flow while they're on the docs page rather than sending them elsewhere.

2. Tableau reader link: We can point folks to the Tableau Reader page instead of the direct download link. Thanks for catching this.

3. Report images: This makes sense too. As Fei said, we can directly link to Google Drive where these images are instead of using the bit.ly passthrough. Bitly helps us measure engagement. To Fei's point, are you able to provide similar statistics via Google Analytics or some other mechanism so we have visibility into engagement?

4. Is there an article or some other reference to the technical writing standards and best practices that we can consult before making docs PRs?

Cheers,
Kal

**Comment by animatedmax** [comment]
Hi Kal,

1. In general, we avoid embedded videos and animated gifs because they are:
* not searchable
* not accessible
* difficult to maintain
* currently impossible for us to provide offline or in PDF form

This particular video has no sound, is presented with no context or explanatory text, is set to autoplay, and even at 1680 x 1050 resolution I could not read the labels on the screen.

2. :D

3. The main issue with bit.ly links is surprising the reader -- if we point out that a particular link will take them to a Google doc, maybe we can justify using bit.ly instead of a cumbersome URL.

4. The rest of the documentation team suggests that I point you to https://docs-wiki.cfapps.io/wiki/index.html, and I don't have a better suggestion at this time.

Hope that helps!

Max

**Comment by kdudala1** [comment]
Thanks, Max! Please see my responses below:

1. We are proposing having embedded videos in addition to not in lieu of searchable text. To make this clearer, we can move the how to opt in video closer to the text instructions for opting in. The Telemetry team would be on the hook for maintaining these videos and ensuring that they continue to work.

Re: offline use cases, are we saying that we are only including materials that are consumable offline even though the primary use case is for these materials to be consumed online?

Thank you for the feedback on resolution. I agree that playing a 4k video in a tiny size is going to lead to readability issues on lower dpi displays. We can certainly reproduce the video at a lower resolution that makes the labels legible.

3. What we need is a way to measure engagement with our documentation. We are not wedded to bit.ly or any other implementation. What alternative mechanisms to measure engagement are available to us either as part of the docs toolset or other approved toolset?

4. Thank you. This is a helpful resource. May I suggest fleshing out the "Style guide" section with some of the technical writing standards and best practices, so teams like ours can consult before making PRs? 

Once we hash out #1 and #3, we can submit a new PR for you to review. Thank you for the rapid feedback.

Cheers,
Kal

**Comment by animatedmax** [comment]
Hi Kal,

Well, if the Telemetry team takes the responsibility for keeping the video updated and working, and the it doesn't replace the searchable text, I don't see a strong reason not to prevent us from embedding it.

I'm also withdrawing my objections to using bit.ly.

I agree with your suggestion about providing more technical writing standards and best practices information in the "Style guide" section of the docs-wiki. Up until recently, the wiki was intended for technical writers only, but now that they've opened it up to non-writers we should add content like that you've suggested.

**Comment by kdudala1** [comment]
Thank you, Max! We'll submit a new PR shortly

**Comment by fyang-pivotal** [comment]
Hey Max,  we made changes to this PR to address your outstanding concerns per the discussion above:

1. We have update the link to the CEIP Opt-in video so that it reflects the Telemetry form workflow for the enhanced tier.
2. We've also updated the link to Tableau Reader so that it doesn't directly downloads the reader but rather point to the download page of Tableau Reader.

Thanks for working with us regarding this PR.

cc: @kdudala1

**Comment by animatedmax** [comment]
Thank you @fyang-pivotal !

**Pull request merged**
