### PR TITLE
Edit AWS docs after following Terraform-AWS script

### PR DESCRIPTION
**Pull request by bu3**
Hi! We have followed some scripts to create AWS environments and found some inconsistencies in the docs, thus, updating the docs.

Reference to the story that led to these changes https://www.pivotaltracker.com/story/show/160412476

[#160412476]

Signed-off-by: Olena Pleshan <opleshan@pivotal.io>

### CODE REVIEW

**Comment by bentarnoff** [comment]
Thanks @bu3! I see you didn't make changes to [Deploying Ops Manager on AWS](https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/aws-om-deploy.html). Are the steps unchanged with the new Terraform template? 

And where can the user find the new Terraform template on Pivnet? Is it still under the Pivotal Application Service section? Or is there a new PKS-specific template which will appear under the Pivotal Container Service section?

**Comment by bentarnoff** [comment]
One more question for you. Now that we've deleted the "Preparing AWS Before Deploying PKS" topic, what guidance should we provide in the "Kubernetes Cloud Provider" section of "Installing PKS on AWS"? https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/installing-pks-aws.html#cloud-provider

Currently we tell users to enter the instance profile names associated with the master and worker nodes, which they would've set up in the "Preparing" topic.

**Comment by bu3** [comment]
@bentarnoff There is a small change to be made on `Deploying Ops Manager on AWS` (PAS -> PKS).
I'll change it

Regarding the second question, it is a little bit more difficult but we'll figure it out and we'll send you another PR to fix the issue

**Comment by bentarnoff** [comment]
Thank you, @bu3 !

**Pull request merged**
