### PR TITLE
1.2.x cidr range 158387175

### PR DESCRIPTION
**Pull request by leeloodub**
Hi! Backporting https://github.com/pivotal-cf/p-pks-integrations/pull/191 into 1.2.x. Thank you!

### CODE REVIEW

**Comment by bentarnoff** [comment]
Hey @leeloodub thanks for this. Would you mind looking at the commit again? It looks like it has a large number of commits and conflicts with the `master` branch. Per the repo [readme](https://github.com/pivotal-cf/docs-pks/blob/master/README.md), `master` currently has pre-release PKS v1.3 content and `1.2` has the published PKS v1.2 docs.

**Comment by neil-hickey** [comment]
hey @bentarnoff I updated the PR to merge to the correct base branch. I assume this is 1.2.

I however see a 1.2.1 branch, should we be merging there? (we aren't sure which patch 1.2.x this will go into though...)

**Comment by bentarnoff** [comment]
Hey @leeloodub @neil-hickey can I ask you to close this PR and then open another PR against a new feature branch I just created for you, `editable-cidr-ranges`? Then we can keep your content on the feature branch until the version of PKS v1.2.x is released with this feature. At that point, please ping us and we will merge the feature branch into the published `1.2` branch. Thank you!

**Comment by neil-hickey** [comment]
will do, thanks ben!

**Pull request closed without merging**
