### PR TITLE
Remove stretch cluster use case from host groups

### PR DESCRIPTION
**Pull request by lparis**

### CODE REVIEW

**Comment by pspinrad** [comment]
Thanks @lparis !  I don't know from stretched clusters, but am wondering if this ref is still legit:
https://github.com/pivotal-cf/docs-pks/blob/1.4/vsphere-persistent-storage.html.md.erb#L75

**Comment by lparis** [comment]
Yes, the reference is still valid Paul. The requested removal of stretch clusters is specific to host groups. We removed it from the 1.6 and 1.5 docs, but missed the 1.4 docs. Thanks.

**Comment by pspinrad** [comment]
Thanks again @lparis - some day soon I hope to know enough to not hafta ask!

**Comment by lparis** [comment]
Have a great holiday break. I'll be available should any more questions arise. Thanks.

**Comment by pspinrad** [comment]
Thank you, Lorenzo-- you have a great one too!  See you  on the other side..

**Pull request merged**
