### PR TITLE
First wave of topics for Gear2 docs

### PR DESCRIPTION
**Pull request by stuclem**
These are the first topics for the Gear2 docs.

@lparis can you please take a look at the formatting and general style to make sure that they conform to the PKS standard?

### CODE REVIEW

**Comment by stuclem** [comment]
@lparis one area where I think I need help is linking. I'm a little fuzzy about how much of the required config that you have documented for vSphere/NSX-T is still applicable in the Gear2 case, so if you can suggest topics that I need to link to from these ones, I would be most grateful.

**Comment by lparis** [comment]
This is good as is. We can review in context on staging and decide what links are needed later since the UI is likely to change. Also, since G2 will support NSX-T 2.5 (my current understanding), I will need to create the 2.5 NSX-T docs for PKS to link to. So, let's address the links later. Thanks.

@animatedmax Can we merge this into Master please for staging review? Thanks.

**Comment by animatedmax** [comment]
Merged and on staging

**Comment by stuclem** [comment]
Thanks @animatedmax and @lparis. I see a few formatting errors, which I will fix today.

**Pull request merged**
